# This workflow will install Python dependencies, run tests and lint with a variety of Python versions
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions
name: Intel OpenVINO / Python - Test

on: [push, pull_request]

jobs:
  build:
    strategy:
      fail-fast: false

    runs-on: ubuntu-18.04
    steps:
    - uses: actions/checkout@v2
    - name: Setup Python 3.7
      uses: actions/setup-python@v2
      with:
        python-version: 3.7
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install flake8 black
        python -m pip install .[intel]
    - name: Check code style
      run: |
        black --check src/optimum/intel/openvino tests/openvino
        flake8 --max-line-length 119 src/optimum/intel/openvino tests/openvino
    - name: Test OpenVINO backend
      working-directory: tests
      run: |
        python -m unittest discover -s openvino -p 'test_*.py'
